name: GitHub Actions Demo
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         output=`git log --format=format:%H,%s`
         output=`ls`
         python ./public/scripts/test.py "$output"
      shell: bash
      env: 
        before: ${{github.event.before}}
        after: ${{github.event.after}}
